### ISSUE TITLE
[BUG]The deducted experience after exceeding the upper limit is incorrect.

### ISSUE THREAD

**Issue by Noogear** [ExplosiveMine/Anvil-Revamp#10]
**Describe the bug**

**To Reproduce**
Keep forging weapons until the experience limit is exceeded. The deducted experience for the part exceeding the limit (level 39) will be doubled.

**Expected behavior**
*

**Screenshots**
As shown in the picture, double the experience was spent.
![QQ20240903-233445](https://github.com/user-attachments/assets/5f642562-40f2-4a2d-ac69-b481e23be9bc)
![QQ20240903-233453](https://github.com/user-attachments/assets/222b923d-d4f6-461d-a20f-299193e84a63)

**Server (please complete the following information):**
 - OS:  windows
 - Type: paper
 - Version: 1.21

**Additional context**
*

**Comment by ExplosiveMine** [comment]
fixed on [latest](https://www.spigotmc.org/resources/anvil-virtual-menu-custom-mechanics-1-17-1-21-1.77142/) release. Pleaes check and let me know if there are more issues. Lastly, thx for the bug report!

**Comment by Noogear** [comment]
> fixed on [latest](https://www.spigotmc.org/resources/anvil-virtual-menu-custom-mechanics-1-17-1-21-1.77142/) release. Pleaes check and let me know if there are more issues. Lastly, thx for the bug report!

Thank you very much for your superman-like rapid fix. I will test it and reply to you as soon as possible.
