### ISSUE TITLE
Players cant see the needed cost in chat post "Too Expensive"

### ISSUE THREAD

**Issue by BanxMagil** [ExplosiveMine/Anvil-Revamp#4]
I'm having an issue where I as an operator can see the too expensive cost in chat, but when players try they cannot. I'm assuming I may need to give my players the anvil.use permission, but I also don't want them to be able to just open an anvil without having one. Any way to fix this?

**Comment by ExplosiveMine** [comment]
Please provide the steps to reproduce the bug or a video/screenshots.
Also provide the version of the plugin (ensure you have the latest), and the server

**Comment by BanxMagil** [comment]
The steps are to an item that is too expensive and not have enough xp to add what you are trying to add to it, it doesn't show up in chat how much you need. I am on the latest version- 1.4.0, the server is running Paper for 1.19.4.

Also found another thing where players couldn't use formatting codes in the anvil, just color. For example bold - &l.

Had one of my players help me test, they could only see the cost once I gave them the "anvil.*" permission. I had given them all the listed permissions before I did that and they couldn't. Naturally I don't want them to have ALL the permissions, just the ones for virtual anvil, color, formatting, and seeing the too expensive cost. Are there some secret permissions?

**Comment by ExplosiveMine** [comment]
I could not find the bug. Please post the detailed step-by-step instructions or a screenshot/video if possible. Regarding the permissions, they seem to work fine as well...
