### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by leonardobarrosbrasil** [ExplosiveMine/Anvil-Revamp#6]
Can you add a command that opens an anvil for another player? /anvil <player> for example

**Comment by ExplosiveMine** [comment]
Yes

**Comment by leonardobarrosbrasil** [comment]
Example: /anvil (player)
Is there a deadline for the update? 😭

**Comment by ExplosiveMine** [comment]
I shall attend to it within the next day or two

**Comment by ExplosiveMine** [comment]
Hello, I've released version 1.4.5-beta which includes your request.  I'd be obliged if you could test it and get back to me.
Please note that there are multiple changes - please read the release notes and download the jar file [here.](https://github.com/ExplosiveMine/Anvil-Revamp/releases/tag/1.4.5-beta)

**Comment by leonardobarrosbrasil** [comment]
So far it's working perfectly. However, I have a doubt. Should the string "TITLE" in lang change the title of the virtual anvil? If yes, it is not working

**Comment by ExplosiveMine** [comment]
Thanks for bringing that up, I'll fix it asap

**Comment by leonardobarrosbrasil** [comment]
Ok 😁

**Comment by leonardobarrosbrasil** [comment]
Hello, are you still alive?

**Comment by ExplosiveMine** [comment]
Sorry, is it urgent?

**Comment by ExplosiveMine** [comment]
added custom titles for 1.19.4+. please check for the new update on spigot and follow the update description on how to add the necessary option in your config.yml.
