### ISSUE TITLE
[BUG] Put item will cause error

### ISSUE THREAD

**Issue by xMikux** [ExplosiveMine/Anvil-Revamp#7]
**Describe the bug**
When I put item into anvil, it will pop up error.

**To Reproduce**
1. Put down an anvil, open it
2. Put some item into, and see the error.

**Expected behavior**
No error should appear.

**Error Log**
https://mclo.gs/YURvLNM

**Server (please complete the following information):**
 - MC Version: Paper 1.21-111-master@66165f7
 - Plugin Version: 1.4.6

**Comment by ExplosiveMine** [comment]
thanks, fixed in latest update
https://www.spigotmc.org/resources/anvil-virtual-menu-custom-mechanics-1-17-1-21.77142/

**Comment by xMikux** [comment]
Thanks! No error now.
