### ISSUE TITLE
[BUG] Disable Virtual Anvil?

### ISSUE THREAD

**Issue by xMikux** [ExplosiveMine/Anvil-Revamp#8]
**Describe the bug**
I am not sure if this is the expected behavior, but when I don't give virtual GUI (or config disable it), anvil color rename and maximum repair cost will not functional (show up default name, and too expensive)

Also, if I give virtual anvil permission, still need open it once (by right click at hand), then color rename and maximum repair cost will be functional. (Relogin need open again too)

**To Reproduce**
1. Make sure your item already too expensive
2. Install Anvil (disable `virtual anvils`) and Luckperms plugin 
3. Add `anvil.colour` permission
4. Test add enchant & rename color
5. See `Too Expensive` and Color code without color!

**Expected behavior**
Should work without use Virtual Anvil.

**Server (please complete the following information):**
 - MC Version: Paper 1.21-111-master@66165f7
 - Plugin Version: 1.4.7

**Comment by ExplosiveMine** [comment]
So the setting `virtual anvils: true` specifically allows players to right click on an anvil item in their hand to open the anvil menu. This is just to avoid having to place the anvil block, then mine it again to pick it up.

**Comment by ExplosiveMine** [comment]
ah I see what you're saying, if the player right clicks a regular anvil with only the anvil.open permission, it's just a regular anvil

**Comment by xMikux** [comment]
I tested with `anvil.open` not work
![image](https://github.com/user-attachments/assets/4cd86a92-3881-4787-9252-1882d8b7b587)
![image](https://github.com/user-attachments/assets/886873c5-15f7-44fb-bf5d-d43d4363cbe0)

also I am not sure, luckperms only show two permission node
![image](https://github.com/user-attachments/assets/1407eb56-d890-4301-814f-c3047668acd2)

**Comment by ExplosiveMine** [comment]
yes, that's just a regular anvil. to access the plugin's anvil for now do /anvil

**Comment by xMikux** [comment]
hmm, so no way to use at regular anvil?
Current I want to use at regular anvil, not any gui.

**Comment by ExplosiveMine** [comment]
set `unbreakable anvils` to false. this makes you access the vanilla anvil. right now you can't use colours or the other features of this plugin in that anvil, but I'll fix that soon

**Comment by xMikux** [comment]
I already set `unbreakable anvils` to false actually, this is why it show up vanilla anvil.

**Comment by ExplosiveMine** [comment]
just to clarify: 

> set `unbreakable anvils` to false. this makes you access the vanilla anvil. right now you can't use colours or the other features of this plugin in that anvil, but I'll fix that soon

this is what you want?

**Comment by xMikux** [comment]
I want using vanilla anvil with color and maximum repair cost.

**Comment by ExplosiveMine** [comment]
you can use this [release ](https://github.com/ExplosiveMine/Anvil-Revamp/releases/tag/1.4.8-beta.1) while I test with all versions, before releasing it on the spigot page. Please tell me if this works as you wanted it to

**Comment by xMikux** [comment]
I tested, it work perfectly! Thank you!
