### ISSUE TITLE
[BUG] 1.21.1 support

### ISSUE THREAD

**Issue by xMikux** [ExplosiveMine/Anvil-Revamp#9]
**Describe the bug**
Install the plugin at 1.21.1 will cause can't open anvil gui.

https://mclo.gs/LcAM0RP

**To Reproduce**
1. Download Paper 1.21.1
2. Install the plugin
3. Try to open anvil!

**Expected behavior**
Should have no error, and correctly open the anvil.

**Server (please complete the following information):**
 - MC Version: 1.21.1-15-master@11b4ac7
- Plugin Version: 1.4.8

**Comment by ExplosiveMine** [comment]
Hi sorry for delay, download available on spigot page
